---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hybris-app
  labels:
    app: {{ .Release.Name }}-hybris-app
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.image.port }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-hybris-app
