---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hybris-app
spec:
  replicas: {{ .Values.image.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-hybris-app
    spec:
      containers:
      - name: {{ .Release.Name }}-hybris-app
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.image.port }}
