apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hybris-app-rollingupdate
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hybris
    spec:
      containers:
      - name: hybris-app
        image: heflik/hybris:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
