apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hybris-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hybris
    spec:
      containers:
      - name: hybris-app
        image: heflik/hybris:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
