apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hybris-app-deployment-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hybris
    spec:
      containers:
      - name: hybris-app
        image: heflik/hybris:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
