apiVersion: v1
kind: Service
metadata:
  name: hybris-service
  labels:
    run: service
spec:
  type: NodePort
  ports:
  - port: 31000
    targetPort: 80
    nodePort: 32000
    protocol: TCP
  selector:
    app: hybris
